[volctos]
type = s3
provider = Other
region = cn-beijing
access_key_id = REPLACE_WITH_REAL_ACCESS_KEY
secret_access_key = REPLACE_WITH_REAL_SECRET_KEY
disable_http2 = true
force_path_style = false
endpoint = tos-s3-cn-beijing.volces.com
